---
title: "Presenters' relevant/past experience"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage{booktabs}
- \usepackage{xcolor}
- \definecolor{link}{rgb}{0, 0, 238}
---

Dr. Anderson has taught R at the University of Oregon for each of the past two
years and is currently leading a five-course data science specialization for
the University of Oregon's College of Education (see the current development
\color{link}[here](https://github.com/uo-datasci-specialization) \color{black}).
In the classes Dr. Anderson teaches, he requires all work be completed in
a reproducible way. Similarly, he has provided training both to faculty at
the UO (for example, see \color{link} [here](https://youtu.be/n-M2ivdofbo)
\color{black}) and at other institutions in a consulting role (for example,
see \color{link}[here](https://github.com/datalorax/FSU_June16)\color{black}).
He has also written multiple conference papers and led many conference
presentations using R Markdown, *GitHub*, and reproducible practices (for
example, see \color{link} [his most recent presentation for NCME](https://
github.com/datalorax/ncme_18)\color{black}).

Dr. Rosenberg recently completed his doctoral dissertation using R Markdown
and reproducible workflows with *GitHub* (see \color{link}[here](https://
github.com/jrosen48/dissertation)\color{black}). He actively develops
statistical software for R, including the \color{link}[konfound R package]
(https://github.com/jrosen48/konfound) \color{black} and \color{link}
[interactive web application](http://konfound-it.com) \color{black} for
sensitivity analysis, and a package that provides an interface to MPlus to make
it easier to carry out certain kinds of mixture models as part of a reproducible
analysis. Dr. Rosenberg has also given invited talks on using R \color{link}
[at Georgia Southern University](http:// rpubs.com/jmichaelrosenberg/164105)
\color{black} and \color{link} [at the School of Criminal Justice at Michigan
State University](/appendix/our- work/rosenberg-r_introduction_4-14-17.html).
\color{black. At Michigan State University and now at the University of
Tennessee, Knoxville, he has mentored peers and graduate students in using R as
part of a reproducible workflow.