---
title: "Transparent and Reproducible Research with R"
shorttitle: "Reproducible Research R"
date: "`r format(Sys.time(), '%B %d, %Y')`"

author: 
  - name          : "Daniel Anderson"
    affiliation   : "1"
    corresponding : yes
    email         : "daniela@uoregon.edu"
    address       : "5262 University of Oregon"
  - name          : "Joshua Rosenberg"
    affiliation   : "2"
    email         : "jrosenb8@utk.edu"

affiliation:
  - id            : "1"
    institution   : "University of Oregon"
  - id            : "2"
    institution   : "University of Tennessee, Knoxville"

bibliography      : refs.bib

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no

class             : "doc"
output            : papaja::apa6_pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Reproducibility of research findings is critical to the validity of inferences
from studies. If an independent evaluator with access to the study data is
unable to reproduce the published findings *exactly*, the trustworthiness of the
findings are called into question, as highlighted by several prominent examples
[e.g., the Duke crisis; see @peng15]. Such issues are also essential in a time
in which established findings are being called into question (i.e., concerns
about the reproducibility of psychological science findings) because of choices
made in the course of a research study.

In this training, we provide an overview of reproducibility and open science,
and introduce participants to tools that increase the
likelihood of reproducible and transparent workflows. We emphasize
tools from the R software environment to weave text with analysis code (e.g.,
R Markdown), version control to document the entire history
of a project, and platforms for sharing analysis workflows publicly.

In the first hour of this four-hour training, we introduce participants to
the ideas motivating open and reproducible research in educational research.
In the second and third hours, we discuss the basics of R Markdown and the 
various formats to which documents can be rendered. Finally, in the fourth hour, 
we provide a primer on version control using *GitHub*. Our target audience is 
early-career scholars as well as researchers at any stage looking for tools to 
help increase the likelihood of their work being reproducible. The format will 
include part lecture and part hands-on applied work.

\newpage
# References